/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import Backend.CPUController;
import Backend.CPUListener;
import Models.Instruction;
import java.awt.Color;
import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.xml.sax.Attributes;

/**
 *
 * @author jimon
 */
public class main_Activity extends javax.swing.JFrame implements CPUListener {


    private int currentInstructionPosition=0;
    private CPUController CPU1;
    private CPUController CPU2;
    private boolean active = false;
    private int screenUsed = 0;
    
    
    /**
     * Creates new form main_Activity
     */
    public main_Activity() {
        initComponents();
        
        textfieldMemorySize.setForeground(new Color(153,153,153));
        CPU1 = new CPUController(getPanelComponents());
        CPU2 = new CPUController(getSecondPanelComponents());
        CPU1.addListener(this);
        CPU2.addListener(this);
        CPU1.setCPUName("CPU1");
        CPU2.setCPUName("CPU2");
        btnUploadFile.setEnabled(false);
        btnExecute.setEnabled(false);
        btnClean.setEnabled(false);
        btnAutoExecute.setEnabled(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textfieldMemorySize = new javax.swing.JTextField();
        btnEnterMemorySize = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnExecute = new javax.swing.JButton();
        btnUploadFile = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jCPU2Instruccion = new javax.swing.JTable();
        jpanelCPU1 = new javax.swing.JPanel();
        lblPC = new javax.swing.JLabel();
        lblIR = new javax.swing.JLabel();
        lblAC = new javax.swing.JLabel();
        lblAX = new javax.swing.JLabel();
        lblBX = new javax.swing.JLabel();
        lblCX = new javax.swing.JLabel();
        lblDX = new javax.swing.JLabel();
        textPC = new javax.swing.JTextField();
        textIR = new javax.swing.JTextField();
        textAC = new javax.swing.JTextField();
        textAX = new javax.swing.JTextField();
        textBX = new javax.swing.JTextField();
        textCX = new javax.swing.JTextField();
        textDX = new javax.swing.JTextField();
        lblAC1 = new javax.swing.JLabel();
        textPila = new javax.swing.JTextField();
        jLabelCPU1 = new javax.swing.JLabel();
        jLabelCPU2 = new javax.swing.JLabel();
        jTextfieldScreen = new javax.swing.JTextField();
        jButtonEnter = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jCPU1Instruccion = new javax.swing.JTable();
        jLabelCPU3 = new javax.swing.JLabel();
        jLabelCPU4 = new javax.swing.JLabel();
        jLabelCPU2Programs = new javax.swing.JLabel();
        jLabelCPU1Programs = new javax.swing.JLabel();
        btnAutoExecute = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jContentScreen = new javax.swing.JTable();
        jpanelCPU6 = new javax.swing.JPanel();
        lblPC5 = new javax.swing.JLabel();
        lblIR5 = new javax.swing.JLabel();
        lblAC9 = new javax.swing.JLabel();
        lblAX5 = new javax.swing.JLabel();
        lblBX5 = new javax.swing.JLabel();
        lblCX5 = new javax.swing.JLabel();
        lblDX5 = new javax.swing.JLabel();
        textPC5 = new javax.swing.JTextField();
        textIR5 = new javax.swing.JTextField();
        textAC5 = new javax.swing.JTextField();
        textAX5 = new javax.swing.JTextField();
        textBX5 = new javax.swing.JTextField();
        textCX5 = new javax.swing.JTextField();
        textDX5 = new javax.swing.JTextField();
        lblAC10 = new javax.swing.JLabel();
        textPila4 = new javax.swing.JTextField();
        jpanelCPU5 = new javax.swing.JPanel();
        lblPC4 = new javax.swing.JLabel();
        lblIR4 = new javax.swing.JLabel();
        lblAC7 = new javax.swing.JLabel();
        lblAX4 = new javax.swing.JLabel();
        lblBX4 = new javax.swing.JLabel();
        lblCX4 = new javax.swing.JLabel();
        lblDX4 = new javax.swing.JLabel();
        textPC4 = new javax.swing.JTextField();
        textIR4 = new javax.swing.JTextField();
        textAC4 = new javax.swing.JTextField();
        textAX4 = new javax.swing.JTextField();
        textBX4 = new javax.swing.JTextField();
        textCX4 = new javax.swing.JTextField();
        textDX4 = new javax.swing.JTextField();
        lblAC8 = new javax.swing.JLabel();
        textPila3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textfieldMemorySize.setText("Enter memory size");
        textfieldMemorySize.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textfieldMemorySizeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textfieldMemorySizeFocusLost(evt);
            }
        });
        textfieldMemorySize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldMemorySizeActionPerformed(evt);
            }
        });
        textfieldMemorySize.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textfieldMemorySizeKeyTyped(evt);
            }
        });
        getContentPane().add(textfieldMemorySize, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 27, 153, 38));

        btnEnterMemorySize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProgramImages/memory.png"))); // NOI18N
        btnEnterMemorySize.setText("Enter");
        btnEnterMemorySize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterMemorySizeActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnterMemorySize, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 27, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setForeground(new java.awt.Color(204, 255, 255));

        btnExecute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProgramImages/play.png"))); // NOI18N
        btnExecute.setText("Execute Step by Step");
        btnExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecuteActionPerformed(evt);
            }
        });

        btnUploadFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProgramImages/upload_file.png"))); // NOI18N
        btnUploadFile.setText("Upload file");
        btnUploadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadFileActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProgramImages/delete.png"))); // NOI18N
        jButton1.setText("Exit");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProgramImages/clean.png"))); // NOI18N
        btnClean.setText("Clean");
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        jCPU2Instruccion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jCPU2Instruccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pos", "Memory Pos", "Instruction", "Weight", "State"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jCPU2Instruccion.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jCPU2Instruccion);
        if (jCPU2Instruccion.getColumnModel().getColumnCount() > 0) {
            jCPU2Instruccion.getColumnModel().getColumn(0).setMinWidth(50);
            jCPU2Instruccion.getColumnModel().getColumn(0).setPreferredWidth(3);
            jCPU2Instruccion.getColumnModel().getColumn(0).setMaxWidth(50);
            jCPU2Instruccion.getColumnModel().getColumn(1).setMinWidth(150);
            jCPU2Instruccion.getColumnModel().getColumn(1).setMaxWidth(150);
            jCPU2Instruccion.getColumnModel().getColumn(2).setMinWidth(200);
            jCPU2Instruccion.getColumnModel().getColumn(2).setMaxWidth(200);
            jCPU2Instruccion.getColumnModel().getColumn(3).setMinWidth(50);
            jCPU2Instruccion.getColumnModel().getColumn(3).setMaxWidth(50);
            jCPU2Instruccion.getColumnModel().getColumn(4).setMinWidth(100);
            jCPU2Instruccion.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        jpanelCPU1.setBackground(new java.awt.Color(204, 255, 255));
        jpanelCPU1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpanelCPU1.setForeground(new java.awt.Color(255, 255, 255));

        lblPC.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblPC.setText("PC:");

        lblIR.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblIR.setText("IR:");

        lblAC.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAC.setText("AC:");

        lblAX.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAX.setText("AX:");

        lblBX.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblBX.setText("BX:");

        lblCX.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCX.setText("CX:");

        lblDX.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDX.setText("DX:");

        textPC.setEditable(false);
        textPC.setBackground(new java.awt.Color(204, 255, 255));
        textPC.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textPC.setText("         ");
        textPC.setBorder(null);
        textPC.setFocusable(false);

        textIR.setEditable(false);
        textIR.setBackground(new java.awt.Color(204, 255, 255));
        textIR.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textIR.setText("    ");
        textIR.setBorder(null);
        textIR.setFocusable(false);

        textAC.setEditable(false);
        textAC.setBackground(new java.awt.Color(204, 255, 255));
        textAC.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textAC.setText("   ");
        textAC.setBorder(null);
        textAC.setFocusable(false);

        textAX.setEditable(false);
        textAX.setBackground(new java.awt.Color(204, 255, 255));
        textAX.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textAX.setText("      ");
        textAX.setBorder(null);
        textAX.setFocusable(false);

        textBX.setEditable(false);
        textBX.setBackground(new java.awt.Color(204, 255, 255));
        textBX.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textBX.setText("    ");
        textBX.setBorder(null);
        textBX.setFocusable(false);

        textCX.setEditable(false);
        textCX.setBackground(new java.awt.Color(204, 255, 255));
        textCX.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textCX.setText("     ");
        textCX.setBorder(null);
        textCX.setFocusable(false);

        textDX.setEditable(false);
        textDX.setBackground(new java.awt.Color(204, 255, 255));
        textDX.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textDX.setText("     ");
        textDX.setBorder(null);
        textDX.setFocusable(false);

        lblAC1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAC1.setText("Stack:");

        textPila.setEditable(false);
        textPila.setBackground(new java.awt.Color(204, 255, 255));
        textPila.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textPila.setText("   ");
        textPila.setBorder(null);
        textPila.setFocusable(false);

        javax.swing.GroupLayout jpanelCPU1Layout = new javax.swing.GroupLayout(jpanelCPU1);
        jpanelCPU1.setLayout(jpanelCPU1Layout);
        jpanelCPU1Layout.setHorizontalGroup(
            jpanelCPU1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelCPU1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpanelCPU1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelCPU1Layout.createSequentialGroup()
                        .addComponent(lblPC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelCPU1Layout.createSequentialGroup()
                        .addComponent(lblAC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textAC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelCPU1Layout.createSequentialGroup()
                        .addComponent(lblIR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textIR, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelCPU1Layout.createSequentialGroup()
                        .addComponent(lblAC1)
                        .addGap(7, 7, 7)
                        .addComponent(textPila, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jpanelCPU1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelCPU1Layout.createSequentialGroup()
                        .addComponent(lblDX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textDX))
                    .addGroup(jpanelCPU1Layout.createSequentialGroup()
                        .addComponent(lblAX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textAX, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                    .addGroup(jpanelCPU1Layout.createSequentialGroup()
                        .addComponent(lblCX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textCX))
                    .addGroup(jpanelCPU1Layout.createSequentialGroup()
                        .addComponent(lblBX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textBX)))
                .addContainerGap())
        );
        jpanelCPU1Layout.setVerticalGroup(
            jpanelCPU1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelCPU1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jpanelCPU1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPC)
                    .addComponent(lblAX)
                    .addComponent(textPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelCPU1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIR)
                    .addComponent(lblBX)
                    .addComponent(textIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelCPU1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAC)
                    .addComponent(lblCX)
                    .addComponent(textAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelCPU1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDX)
                    .addComponent(textDX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAC1)
                    .addComponent(textPila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelCPU1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelCPU1.setText("CPU 1");

        jLabelCPU2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelCPU2.setText("CPU 2");

        jTextfieldScreen.setEnabled(false);
        jTextfieldScreen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextfieldScreenKeyTyped(evt);
            }
        });

        jButtonEnter.setText("Enter");
        jButtonEnter.setEnabled(false);
        jButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterActionPerformed(evt);
            }
        });

        jCPU1Instruccion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jCPU1Instruccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pos", "Memory Pos", "Instruction", "Weight", "State"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jCPU1Instruccion.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jCPU1Instruccion);
        if (jCPU1Instruccion.getColumnModel().getColumnCount() > 0) {
            jCPU1Instruccion.getColumnModel().getColumn(0).setMinWidth(50);
            jCPU1Instruccion.getColumnModel().getColumn(0).setPreferredWidth(3);
            jCPU1Instruccion.getColumnModel().getColumn(0).setMaxWidth(50);
            jCPU1Instruccion.getColumnModel().getColumn(1).setMinWidth(150);
            jCPU1Instruccion.getColumnModel().getColumn(1).setMaxWidth(150);
            jCPU1Instruccion.getColumnModel().getColumn(2).setMinWidth(200);
            jCPU1Instruccion.getColumnModel().getColumn(2).setMaxWidth(200);
            jCPU1Instruccion.getColumnModel().getColumn(3).setMinWidth(50);
            jCPU1Instruccion.getColumnModel().getColumn(3).setMaxWidth(50);
            jCPU1Instruccion.getColumnModel().getColumn(4).setMinWidth(100);
            jCPU1Instruccion.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        jLabelCPU3.setText("Programs in queue :");

        jLabelCPU4.setText("Programs in queue :");

        btnAutoExecute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProgramImages/play.png"))); // NOI18N
        btnAutoExecute.setText("Automatic Execution");
        btnAutoExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoExecuteActionPerformed(evt);
            }
        });

        jContentScreen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jContentScreen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Message"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jContentScreen.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(jContentScreen);
        if (jContentScreen.getColumnModel().getColumnCount() > 0) {
            jContentScreen.getColumnModel().getColumn(0).setMinWidth(50);
            jContentScreen.getColumnModel().getColumn(0).setPreferredWidth(3);
            jContentScreen.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jpanelCPU6.setBackground(new java.awt.Color(204, 255, 255));
        jpanelCPU6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpanelCPU6.setForeground(new java.awt.Color(255, 255, 255));

        lblPC5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblPC5.setText("PC:");

        lblIR5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblIR5.setText("IR:");

        lblAC9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAC9.setText("AC:");

        lblAX5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAX5.setText("AX:");

        lblBX5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblBX5.setText("BX:");

        lblCX5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCX5.setText("CX:");

        lblDX5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDX5.setText("DX:");

        textPC5.setEditable(false);
        textPC5.setBackground(new java.awt.Color(204, 255, 255));
        textPC5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textPC5.setText("         ");
        textPC5.setBorder(null);
        textPC5.setFocusable(false);

        textIR5.setEditable(false);
        textIR5.setBackground(new java.awt.Color(204, 255, 255));
        textIR5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textIR5.setText("    ");
        textIR5.setBorder(null);
        textIR5.setFocusable(false);

        textAC5.setEditable(false);
        textAC5.setBackground(new java.awt.Color(204, 255, 255));
        textAC5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textAC5.setText("   ");
        textAC5.setBorder(null);
        textAC5.setFocusable(false);

        textAX5.setEditable(false);
        textAX5.setBackground(new java.awt.Color(204, 255, 255));
        textAX5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textAX5.setText("      ");
        textAX5.setBorder(null);
        textAX5.setFocusable(false);

        textBX5.setEditable(false);
        textBX5.setBackground(new java.awt.Color(204, 255, 255));
        textBX5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textBX5.setText("    ");
        textBX5.setBorder(null);
        textBX5.setFocusable(false);

        textCX5.setEditable(false);
        textCX5.setBackground(new java.awt.Color(204, 255, 255));
        textCX5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textCX5.setText("     ");
        textCX5.setBorder(null);
        textCX5.setFocusable(false);

        textDX5.setEditable(false);
        textDX5.setBackground(new java.awt.Color(204, 255, 255));
        textDX5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textDX5.setText("     ");
        textDX5.setBorder(null);
        textDX5.setFocusable(false);

        lblAC10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAC10.setText("Stack:");

        textPila4.setEditable(false);
        textPila4.setBackground(new java.awt.Color(204, 255, 255));
        textPila4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textPila4.setText("   ");
        textPila4.setBorder(null);
        textPila4.setFocusable(false);

        javax.swing.GroupLayout jpanelCPU6Layout = new javax.swing.GroupLayout(jpanelCPU6);
        jpanelCPU6.setLayout(jpanelCPU6Layout);
        jpanelCPU6Layout.setHorizontalGroup(
            jpanelCPU6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelCPU6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpanelCPU6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelCPU6Layout.createSequentialGroup()
                        .addComponent(lblPC5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPC5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelCPU6Layout.createSequentialGroup()
                        .addComponent(lblAC9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textAC5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelCPU6Layout.createSequentialGroup()
                        .addComponent(lblIR5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textIR5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelCPU6Layout.createSequentialGroup()
                        .addComponent(lblAC10)
                        .addGap(7, 7, 7)
                        .addComponent(textPila4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jpanelCPU6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelCPU6Layout.createSequentialGroup()
                        .addComponent(lblDX5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textDX5))
                    .addGroup(jpanelCPU6Layout.createSequentialGroup()
                        .addComponent(lblAX5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textAX5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                    .addGroup(jpanelCPU6Layout.createSequentialGroup()
                        .addComponent(lblCX5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textCX5))
                    .addGroup(jpanelCPU6Layout.createSequentialGroup()
                        .addComponent(lblBX5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textBX5)))
                .addContainerGap())
        );
        jpanelCPU6Layout.setVerticalGroup(
            jpanelCPU6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelCPU6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jpanelCPU6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPC5)
                    .addComponent(lblAX5)
                    .addComponent(textPC5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAX5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelCPU6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIR5)
                    .addComponent(lblBX5)
                    .addComponent(textIR5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBX5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelCPU6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAC9)
                    .addComponent(lblCX5)
                    .addComponent(textAC5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCX5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelCPU6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDX5)
                    .addComponent(textDX5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAC10)
                    .addComponent(textPila4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelCPU1)
                            .addGap(39, 39, 39)
                            .addComponent(jLabelCPU3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabelCPU1Programs, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jpanelCPU1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelCPU2)
                        .addGap(45, 45, 45)
                        .addComponent(jLabelCPU4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelCPU2Programs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpanelCPU6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnUploadFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAutoExecute, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExecute)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextfieldScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jButtonEnter)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUploadFile, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExecute, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAutoExecute, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextfieldScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonEnter))
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelCPU1)
                                .addComponent(jLabelCPU3)
                                .addComponent(jLabelCPU1Programs))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jpanelCPU1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(46, 46, 46)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelCPU2)
                                .addComponent(jLabelCPU4)
                                .addComponent(jLabelCPU2Programs))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jpanelCPU6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(11, 11, 11)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 690));

        jpanelCPU5.setBackground(new java.awt.Color(204, 255, 255));
        jpanelCPU5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpanelCPU5.setForeground(new java.awt.Color(255, 255, 255));

        lblPC4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblPC4.setText("PC:");

        lblIR4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblIR4.setText("IR:");

        lblAC7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAC7.setText("AC:");

        lblAX4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAX4.setText("AX:");

        lblBX4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblBX4.setText("BX:");

        lblCX4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCX4.setText("CX:");

        lblDX4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDX4.setText("DX:");

        textPC4.setEditable(false);
        textPC4.setBackground(new java.awt.Color(204, 255, 255));
        textPC4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textPC4.setText("         ");
        textPC4.setBorder(null);
        textPC4.setFocusable(false);

        textIR4.setEditable(false);
        textIR4.setBackground(new java.awt.Color(204, 255, 255));
        textIR4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textIR4.setText("    ");
        textIR4.setBorder(null);
        textIR4.setFocusable(false);

        textAC4.setEditable(false);
        textAC4.setBackground(new java.awt.Color(204, 255, 255));
        textAC4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textAC4.setText("   ");
        textAC4.setBorder(null);
        textAC4.setFocusable(false);

        textAX4.setEditable(false);
        textAX4.setBackground(new java.awt.Color(204, 255, 255));
        textAX4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textAX4.setText("      ");
        textAX4.setBorder(null);
        textAX4.setFocusable(false);

        textBX4.setEditable(false);
        textBX4.setBackground(new java.awt.Color(204, 255, 255));
        textBX4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textBX4.setText("    ");
        textBX4.setBorder(null);
        textBX4.setFocusable(false);

        textCX4.setEditable(false);
        textCX4.setBackground(new java.awt.Color(204, 255, 255));
        textCX4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textCX4.setText("     ");
        textCX4.setBorder(null);
        textCX4.setFocusable(false);

        textDX4.setEditable(false);
        textDX4.setBackground(new java.awt.Color(204, 255, 255));
        textDX4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textDX4.setText("     ");
        textDX4.setBorder(null);
        textDX4.setFocusable(false);

        lblAC8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAC8.setText("Stack:");

        textPila3.setEditable(false);
        textPila3.setBackground(new java.awt.Color(204, 255, 255));
        textPila3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textPila3.setText("   ");
        textPila3.setBorder(null);
        textPila3.setFocusable(false);

        javax.swing.GroupLayout jpanelCPU5Layout = new javax.swing.GroupLayout(jpanelCPU5);
        jpanelCPU5.setLayout(jpanelCPU5Layout);
        jpanelCPU5Layout.setHorizontalGroup(
            jpanelCPU5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelCPU5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpanelCPU5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelCPU5Layout.createSequentialGroup()
                        .addComponent(lblPC4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPC4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelCPU5Layout.createSequentialGroup()
                        .addComponent(lblAC7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textAC4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelCPU5Layout.createSequentialGroup()
                        .addComponent(lblIR4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textIR4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelCPU5Layout.createSequentialGroup()
                        .addComponent(lblAC8)
                        .addGap(7, 7, 7)
                        .addComponent(textPila3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jpanelCPU5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelCPU5Layout.createSequentialGroup()
                        .addComponent(lblDX4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textDX4))
                    .addGroup(jpanelCPU5Layout.createSequentialGroup()
                        .addComponent(lblAX4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textAX4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                    .addGroup(jpanelCPU5Layout.createSequentialGroup()
                        .addComponent(lblCX4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textCX4))
                    .addGroup(jpanelCPU5Layout.createSequentialGroup()
                        .addComponent(lblBX4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textBX4)))
                .addContainerGap())
        );
        jpanelCPU5Layout.setVerticalGroup(
            jpanelCPU5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelCPU5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jpanelCPU5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPC4)
                    .addComponent(lblAX4)
                    .addComponent(textPC4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAX4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelCPU5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIR4)
                    .addComponent(lblBX4)
                    .addComponent(textIR4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBX4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelCPU5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAC7)
                    .addComponent(lblCX4)
                    .addComponent(textAC4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCX4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelCPU5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDX4)
                    .addComponent(textDX4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAC8)
                    .addComponent(textPila3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jpanelCPU5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void detectCPUSQueue(){
        int cpu1queue = CPU1.getRemainingPrograms();
        int cpu2queue = CPU2.getRemainingPrograms();
        jLabelCPU1Programs.setText(String.valueOf(cpu1queue));
        jLabelCPU2Programs.setText(String.valueOf(cpu2queue));
    }
    
    private void textfieldMemorySizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldMemorySizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldMemorySizeActionPerformed

    private void textfieldMemorySizeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldMemorySizeFocusGained
        if (textfieldMemorySize.getText().equals("Enter memory size")){
            textfieldMemorySize.setText("");
            textfieldMemorySize.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_textfieldMemorySizeFocusGained

    private void textfieldMemorySizeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldMemorySizeFocusLost
         if (textfieldMemorySize.getText().equals("")){
            textfieldMemorySize.setText("Enter memory size");
            textfieldMemorySize.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_textfieldMemorySizeFocusLost

    private void textfieldMemorySizeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldMemorySizeKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_textfieldMemorySizeKeyTyped

    private void btnEnterMemorySizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterMemorySizeActionPerformed
        String memorySizeString = textfieldMemorySize.getText();
        CpuMemoryDialog popup = new CpuMemoryDialog(this, true);
        popup.setSize(280, 210);
        popup.setFocusable(false);
        popup.setVisible(true);
        int[] cpuMemorySizeArray = popup.getCpuMemorySize();
        CPU1.setMemorySize(cpuMemorySizeArray[0]);
        CPU2.setMemorySize(cpuMemorySizeArray[1]);
        btnUploadFile.setEnabled(true);
        JOptionPane.showMessageDialog(this, "The memory for CPU#1 is "+cpuMemorySizeArray[0]+"\n"+"The memory for CPU#2 is "+cpuMemorySizeArray[1],
                "Valid value", 
                JOptionPane.INFORMATION_MESSAGE);
      
        
    }//GEN-LAST:event_btnEnterMemorySizeActionPerformed

    private void btnAutoExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoExecuteActionPerformed
        active = !active;

        Thread thread = new Thread(new Runnable() {
            @Override
            public void run() {
                while (active) {

                    executeDualCPU();

                    // Actualizar la interfaz gráfica
                    SwingUtilities.invokeLater(new Runnable() {
                        public void run() {
                            repaint();
                        }
                    });

                    // Agregar un delay de 2 segundos
                    try {
                        Thread.sleep(1000); // 2000 milisegundos = 2 segundos
                    } catch (InterruptedException ex) {
                        // Manejar la excepción si se interrumpe el hilo
                        ex.printStackTrace();
                    }
                }
            }
        });
        thread.start();
    }//GEN-LAST:event_btnAutoExecuteActionPerformed

    private void jButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterActionPerformed
        int textFieldValue = Integer.parseInt(jTextfieldScreen.getText());

        if (textFieldValue > 255){
            JOptionPane.showMessageDialog(this, "The value input should be least than 255",
                "Value writting exceded estimated", JOptionPane.INFORMATION_MESSAGE);
        }else{
            Temporal.onInt09h_aux(textFieldValue);
            jTextfieldScreen.setEnabled(false);
            jButtonEnter.setEnabled(false);
            jTextfieldScreen.setText("");

            DefaultTableModel model = (DefaultTableModel) jContentScreen.getModel();
            String message = "Value Saved";
            String data[] = {String.valueOf(screenUsed),message};
            model.addRow(data);
            screenUsed++;
            jContentScreen.setModel(model);
        }
    }//GEN-LAST:event_jButtonEnterActionPerformed

    private void jTextfieldScreenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextfieldScreenKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            jTextfieldScreen.setText(jTextfieldScreen.getText() + c);
        }
    }//GEN-LAST:event_jTextfieldScreenKeyTyped

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        this.dispose();
        main_Activity newFrame = new main_Activity();
        newFrame.setVisible(true);
    }//GEN-LAST:event_btnCleanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnUploadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadFileActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(true);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.ASM","ASM");
        chooser.setFileFilter(filter);
        int selection = chooser.showOpenDialog(this);
        if(selection == JFileChooser.APPROVE_OPTION){

            File[] files = chooser.getSelectedFiles();
            ArrayList<String> ProgramQueue1 = new ArrayList<String>();
            ArrayList<String> ProgramQueue2= new ArrayList<String>();

            for (int i = 0; i < files.length; i++){
                Random rand = new Random();
                int randomValue = rand.nextInt() % 2;
                if (randomValue==0){ProgramQueue1.add( (files[i]).getAbsolutePath());}
                else{ProgramQueue2.add( (files[i]).getAbsolutePath());}
            }
            try {
                if( (CPU1.loadInstructions(ProgramQueue1,jCPU1Instruccion)) &&  (CPU2.loadInstructions(ProgramQueue2,jCPU2Instruccion))){
                    btnExecute.setEnabled(true);
                    btnAutoExecute.setEnabled(true);
                    btnClean.setEnabled(true);
                    btnUploadFile.setEnabled(false);
                    detectCPUSQueue();
                }else{
                    JOptionPane.showMessageDialog(this, "The available memory is not enough to load the program", "Insufficient space", JOptionPane.ERROR_MESSAGE);
                    btnClean.setEnabled(true);
                }

            } catch (IOException ex) {
                Logger.getLogger(main_Activity.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnUploadFileActionPerformed

    private void btnExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecuteActionPerformed
        executeDualCPU();
    }//GEN-LAST:event_btnExecuteActionPerformed
    
    private void executeDualCPU(){
        if (CPU1.getState()==1){CPU1.executeInstruction();}
        if (CPU2.getState()==1){CPU2.executeInstruction();}
    }
    
    
    private ArrayList<JTextField> getPanelComponents(){
        ArrayList<JTextField> list = new ArrayList<JTextField>();
        Component[] components = jpanelCPU1.getComponents();
        for (Component component : components) {
            if (component.getClass().equals(JTextField.class)) {
                list.add((JTextField)component);
            }
        }
        return list;
    }
    
    private ArrayList<JTextField> getSecondPanelComponents(){
        ArrayList<JTextField> list = new ArrayList<JTextField>();
        Component[] components = jpanelCPU6.getComponents();
        for (Component component : components) {
            if (component.getClass().equals(JTextField.class)) {
                list.add((JTextField)component);
            }
        }
        return list;
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_Activity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutoExecute;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnEnterMemorySize;
    private javax.swing.JButton btnExecute;
    private javax.swing.JButton btnUploadFile;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JTable jCPU1Instruccion;
    private javax.swing.JTable jCPU2Instruccion;
    private javax.swing.JTable jContentScreen;
    private javax.swing.JLabel jLabelCPU1;
    private javax.swing.JLabel jLabelCPU1Programs;
    private javax.swing.JLabel jLabelCPU2;
    private javax.swing.JLabel jLabelCPU2Programs;
    private javax.swing.JLabel jLabelCPU3;
    private javax.swing.JLabel jLabelCPU4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextfieldScreen;
    private javax.swing.JPanel jpanelCPU1;
    private javax.swing.JPanel jpanelCPU2;
    private javax.swing.JPanel jpanelCPU3;
    private javax.swing.JPanel jpanelCPU5;
    private javax.swing.JPanel jpanelCPU6;
    private javax.swing.JLabel lblAC;
    private javax.swing.JLabel lblAC1;
    private javax.swing.JLabel lblAC10;
    private javax.swing.JLabel lblAC2;
    private javax.swing.JLabel lblAC3;
    private javax.swing.JLabel lblAC4;
    private javax.swing.JLabel lblAC5;
    private javax.swing.JLabel lblAC7;
    private javax.swing.JLabel lblAC8;
    private javax.swing.JLabel lblAC9;
    private javax.swing.JLabel lblAX;
    private javax.swing.JLabel lblAX1;
    private javax.swing.JLabel lblAX2;
    private javax.swing.JLabel lblAX4;
    private javax.swing.JLabel lblAX5;
    private javax.swing.JLabel lblBX;
    private javax.swing.JLabel lblBX1;
    private javax.swing.JLabel lblBX2;
    private javax.swing.JLabel lblBX4;
    private javax.swing.JLabel lblBX5;
    private javax.swing.JLabel lblCX;
    private javax.swing.JLabel lblCX1;
    private javax.swing.JLabel lblCX2;
    private javax.swing.JLabel lblCX4;
    private javax.swing.JLabel lblCX5;
    private javax.swing.JLabel lblDX;
    private javax.swing.JLabel lblDX1;
    private javax.swing.JLabel lblDX2;
    private javax.swing.JLabel lblDX4;
    private javax.swing.JLabel lblDX5;
    private javax.swing.JLabel lblIR;
    private javax.swing.JLabel lblIR1;
    private javax.swing.JLabel lblIR2;
    private javax.swing.JLabel lblIR4;
    private javax.swing.JLabel lblIR5;
    private javax.swing.JLabel lblPC;
    private javax.swing.JLabel lblPC1;
    private javax.swing.JLabel lblPC2;
    private javax.swing.JLabel lblPC4;
    private javax.swing.JLabel lblPC5;
    private javax.swing.JTextField textAC;
    private javax.swing.JTextField textAC1;
    private javax.swing.JTextField textAC2;
    private javax.swing.JTextField textAC4;
    private javax.swing.JTextField textAC5;
    private javax.swing.JTextField textAX;
    private javax.swing.JTextField textAX1;
    private javax.swing.JTextField textAX2;
    private javax.swing.JTextField textAX4;
    private javax.swing.JTextField textAX5;
    private javax.swing.JTextField textBX;
    private javax.swing.JTextField textBX1;
    private javax.swing.JTextField textBX2;
    private javax.swing.JTextField textBX4;
    private javax.swing.JTextField textBX5;
    private javax.swing.JTextField textCX;
    private javax.swing.JTextField textCX1;
    private javax.swing.JTextField textCX2;
    private javax.swing.JTextField textCX4;
    private javax.swing.JTextField textCX5;
    private javax.swing.JTextField textDX;
    private javax.swing.JTextField textDX1;
    private javax.swing.JTextField textDX2;
    private javax.swing.JTextField textDX4;
    private javax.swing.JTextField textDX5;
    private javax.swing.JTextField textIR;
    private javax.swing.JTextField textIR1;
    private javax.swing.JTextField textIR2;
    private javax.swing.JTextField textIR4;
    private javax.swing.JTextField textIR5;
    private javax.swing.JTextField textPC;
    private javax.swing.JTextField textPC1;
    private javax.swing.JTextField textPC2;
    private javax.swing.JTextField textPC4;
    private javax.swing.JTextField textPC5;
    private javax.swing.JTextField textPila;
    private javax.swing.JTextField textPila1;
    private javax.swing.JTextField textPila2;
    private javax.swing.JTextField textPila3;
    private javax.swing.JTextField textPila4;
    private javax.swing.JTextField textfieldMemorySize;
    // End of variables declaration//GEN-END:variables

    
    
    
    // Beginning of Interface error listener functions
    @Override
    public void onNoMoreInstructionsAndPrograms(CPUController cpu) {
         JOptionPane.showMessageDialog(this, "There are no further instructions to execute on "+cpu.getCPUName(), 
                 "List of instructions finalised", JOptionPane.INFORMATION_MESSAGE);
         if (CPU1.getState() == 0 && CPU2.getState()==0){
             JOptionPane.showMessageDialog(this, "List of instructions finalised", 
                     "There are no further instructions to execute on both cpu´s", JOptionPane.INFORMATION_MESSAGE);
             btnExecute.setEnabled(false);
             btnAutoExecute.setEnabled(false);
             active = false;
         }
    }

    @Override
    public void onInstructionNotImplemented(CPUController cpu) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    public void onLoadingFileError(CPUController cpu) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void onProgramChanged(CPUController cpu) {
        detectCPUSQueue();
    }
    
    public void onInt10h(int memoryDX) {
        
        
        DefaultTableModel model = (DefaultTableModel) jContentScreen.getModel();
        String message = "DX value = "+ String.valueOf(memoryDX);         
        String data[] = {String.valueOf(screenUsed),message};
        model.addRow(data);
        screenUsed++;
        jContentScreen.setModel(model);
    }
   
    private CPUController Temporal;
    public void onInt09h(CPUController cpu) {
        if(active == true){active = false;}
        JOptionPane.showMessageDialog(this, "Please write the number on the keyboard and press ENTER", 
                "Waiting for the user", JOptionPane.INFORMATION_MESSAGE);
        
        jTextfieldScreen.setEnabled(true);
        jButtonEnter.setEnabled(true); 
        Temporal = cpu;
        
    }

    @Override
    public void onInt21h(CPUController cpu, String secondaryRegister) {
        DefaultTableModel model = (DefaultTableModel) jContentScreen.getModel();
        String message;
        switch(secondaryRegister){
            case "3ch":
                message = "File Created";
                break;
            case "3dh":
                message = "File Open";
                break;
            case "4dh":
                message = "File Read";
                break;
            case "40h":
                message = "File Writen";
                break;
            case "41h":
                message = "File Del";
                break;        
            default:
                message = "Error on 21H";;
            
        }           
        String data[] = {String.valueOf(screenUsed),message};
        model.addRow(data);
        screenUsed++;
        jContentScreen.setModel(model);
    }

    
    public void onCMP(int register1, int register2) {
        DefaultTableModel model = (DefaultTableModel) jContentScreen.getModel();
        String message;
        if (register1 == register2){message = "Equals";}  
        else if (register1 > register2 ){message = "Greater";} 
        else{message = "Less";} 
        String data[] = {String.valueOf(screenUsed),message};
        model.addRow(data);
        screenUsed++;
        jContentScreen.setModel(model);
    }
    
    
    
    
}
